include_guard(GLOBAL)

option(MIND_SIM_ENABLE_GPU "Enable CoreNEURON OpenACC GPU backend for the micro runtime" OFF)
set(MIND_SIM_GPU_ARCHS "lineinfo" CACHE STRING "NVHPC -gpu option list for MIND_Sim GPU builds")

set(CMAKE_CXX_STANDARD 20)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_CXX_EXTENSIONS OFF)
set(CMAKE_POSITION_INDEPENDENT_CODE ON)

if(CMAKE_CXX_COMPILER_ID MATCHES "GNU|Clang|AppleClang")
  set(CMAKE_CXX_FLAGS_RELEASE "-O2 -DNDEBUG" CACHE STRING "Release C++ flags" FORCE)
elseif(CMAKE_CXX_COMPILER_ID MATCHES "NVHPC|PGI")
  set(CMAKE_CXX_FLAGS_RELEASE "-O2 -DNDEBUG" CACHE STRING "Release C++ flags" FORCE)
endif()

find_package(OpenMP REQUIRED)

set(MIND_SIM_MODCC_BACKEND "cpu")
set(MIND_SIM_GPU_COMPILE_OPTIONS)
set(MIND_SIM_GPU_LINK_OPTIONS)
set(MIND_SIM_MODCC_GPU_DEFINE_ARGS)
set(MIND_SIM_GPU_RUNTIME_LIBRARY)

if(MIND_SIM_ENABLE_GPU)
  if(NOT CMAKE_CXX_COMPILER_ID MATCHES "NVHPC|PGI")
    message(FATAL_ERROR "MIND_SIM_ENABLE_GPU requires the NVIDIA HPC SDK C++ compiler (nvc++).")
  endif()
  set(MIND_SIM_MODCC_BACKEND "openacc")
  set(MIND_SIM_RUNTIME_FP_FLAGS "-O2")
  set(MIND_SIM_MODCC_FP_FLAGS "-O2" "-Mautoinline")
  set(MIND_SIM_GPU_COMPILE_OPTIONS "-cuda" "-gpu=${MIND_SIM_GPU_ARCHS}" "-acc")
  set(MIND_SIM_GPU_LINK_OPTIONS "-cuda" "-gpu=${MIND_SIM_GPU_ARCHS}" "-acc")
  list(APPEND MIND_SIM_MODCC_FP_FLAGS "-DR123_USE_INTRIN_H=0" "-DEIGEN_DONT_VECTORIZE=1")
  list(APPEND MIND_SIM_MODCC_GPU_DEFINE_ARGS
    --define CORENEURON_ENABLE_GPU
    --define R123_USE_INTRIN_H=0
    --define EIGEN_DONT_VECTORIZE=1
  )
  find_package(CUDAToolkit QUIET)
  if(CUDAToolkit_FOUND)
    set(MIND_SIM_GPU_RUNTIME_LIBRARY CUDA::cudart)
  else()
    get_filename_component(MIND_SIM_NVHPC_BIN_DIR "${CMAKE_CXX_COMPILER}" DIRECTORY)
    get_filename_component(MIND_SIM_NVHPC_COMPILER_DIR "${MIND_SIM_NVHPC_BIN_DIR}" DIRECTORY)
    get_filename_component(MIND_SIM_NVHPC_VERSION_DIR "${MIND_SIM_NVHPC_COMPILER_DIR}" DIRECTORY)
    file(GLOB MIND_SIM_CUDART_CANDIDATES
      "${MIND_SIM_NVHPC_VERSION_DIR}/cuda/*/targets/x86_64-linux/lib/libcudart.so"
    )
    list(SORT MIND_SIM_CUDART_CANDIDATES)
    list(LENGTH MIND_SIM_CUDART_CANDIDATES MIND_SIM_CUDART_CANDIDATE_COUNT)
    if(MIND_SIM_CUDART_CANDIDATE_COUNT GREATER 0)
      list(GET MIND_SIM_CUDART_CANDIDATES -1 MIND_SIM_GPU_RUNTIME_LIBRARY)
    else()
      message(FATAL_ERROR "Could not locate libcudart for the MIND_Sim GPU build.")
    endif()
  endif()
else()
  set(MIND_SIM_RUNTIME_FP_FLAGS
    "-O3" "-march=native" "-mtune=native" "-fno-math-errno"
    "-ffp-contract=off" "-fno-semantic-interposition" "-funroll-loops"
  )
  set(MIND_SIM_MODCC_FP_FLAGS ${MIND_SIM_RUNTIME_FP_FLAGS})
endif()

list(APPEND MIND_SIM_MODCC_FP_FLAGS ${MIND_SIM_GPU_COMPILE_OPTIONS})
string(REPLACE ";" " " MIND_SIM_MODCC_FP_FLAGS_TEXT "${MIND_SIM_MODCC_FP_FLAGS}")
string(STRIP "${OpenMP_CXX_FLAGS} ${MIND_SIM_MODCC_FP_FLAGS_TEXT}" MIND_SIM_MODCC_CXX_FLAGS)

set(MIND_SIM_MODCC_LINK_OPTIONS ${OpenMP_CXX_FLAGS})
list(APPEND MIND_SIM_MODCC_LINK_OPTIONS ${MIND_SIM_GPU_LINK_OPTIONS})
if(OpenMP_CXX_LIBRARIES)
  if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
    list(APPEND MIND_SIM_MODCC_LINK_OPTIONS "-Wl,--no-as-needed")
  endif()
  list(APPEND MIND_SIM_MODCC_LINK_OPTIONS ${OpenMP_CXX_LIBRARIES})
  if(CMAKE_SYSTEM_NAME STREQUAL "Linux")
    list(APPEND MIND_SIM_MODCC_LINK_OPTIONS "-Wl,--as-needed")
  endif()
endif()
string(REPLACE ";" " " MIND_SIM_MODCC_LINK_FLAGS "${MIND_SIM_MODCC_LINK_OPTIONS}")
