if(NOT REG_CPP)
  message(FATAL_ERROR "write_modl_reg.cmake requires REG_CPP")
endif()
if(NOT FUNCTION_NAME)
  message(FATAL_ERROR "write_modl_reg.cmake requires FUNCTION_NAME")
endif()
if(NOT MOD_NAMES)
  message(FATAL_ERROR "write_modl_reg.cmake requires MOD_NAMES")
endif()

string(REPLACE "," ";" MOD_NAME_LIST "${MOD_NAMES}")

file(WRITE "${REG_CPP}" "#include <cstdio>\n")
file(APPEND "${REG_CPP}" "namespace coreneuron {\n")
file(APPEND "${REG_CPP}" "extern int nrnmpi_myid;\n")
file(APPEND "${REG_CPP}" "extern int nrn_nobanner_;\n")
foreach(name IN LISTS MOD_NAME_LIST)
  file(APPEND "${REG_CPP}" "extern void _${name}_reg();\n")
endforeach()
file(APPEND "${REG_CPP}" "void ${FUNCTION_NAME}() {\n")
file(APPEND "${REG_CPP}" "    if (!nrn_nobanner_ && nrnmpi_myid < 1) {\n")
file(APPEND "${REG_CPP}" "        std::fprintf(stderr, \" Additional MIND_Sim mechanisms from MOD files\\n\");\n")
foreach(name IN LISTS MOD_NAME_LIST)
  file(APPEND "${REG_CPP}" "        std::fprintf(stderr, \" ${name}.mod\");\n")
endforeach()
file(APPEND "${REG_CPP}" "        std::fprintf(stderr, \"\\n\\n\");\n")
file(APPEND "${REG_CPP}" "    }\n")
foreach(name IN LISTS MOD_NAME_LIST)
  file(APPEND "${REG_CPP}" "    _${name}_reg();\n")
endforeach()
file(APPEND "${REG_CPP}" "}\n")
file(APPEND "${REG_CPP}" "}\n")
